# 服务端口
server:
  port: 8004
# 服务名(cloud)
#spring.application.name=user

# 环境设置：dev、test、prod
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze4l01u0xqle8drn6o.mysql.rds.aliyuncs.com:3306/ia_system?zeroDateTimeBehavior=convertToNull&amp
    username: maphsge7
    password: myroot@123
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/xml/*.xml # 这个是最重要的一句，没有这句，识别不出mapper.xml文件，启动时候控制台会报“找不到”



# 设置日志级别
#logging.level.root=INFO
#mybatis日志

